services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: ["uv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./example:/app/example
    restart: unless-stopped
